Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: src/update-task-dns.handler
      CodeUri: E:\Projects\updateDNS
      Runtime: nodejs18.x
      Architectures:
        - x86_64